language: java
jdk:
  - oraclejdk7
cache:
  directories:
  - .cache/intellij

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  matrix:
    - IJ_ULTIMATE=false
    - IJ_ULTIMATE=true
    - USE_PANTS_TO_COMPILE=false
    - USE_ISOLATED_STRATEGY=false
    - PANTS_SHA=261bb71418f2605ff397d74b589cc74fed88bcda TEST_SET=integration # 0.0.36
    - PANTS_SHA=69a95616bc5ab498166adf939e5634e6fa2ff0ae TEST_SET=integration # 0.0.35
    - PANTS_SHA=c2342bb240321a7bd53adec744abf6246a20492e TEST_SET=integration # 0.0.34
    - PANTS_SHA=80a24682e3c7fe16a0323219cd4b07819c30714b TEST_SET=integration # 0.0.33

script:
  - ./scripts/run-tests-ci.sh
  - ./scripts/run-custom-integration.sh
      -r ./.cache/pants
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
