language: java
jdk:
  - oraclejdk7
cache:
  directories:
  - .cache/intellij

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  matrix:
    - IJ_ULTIMATE=false
    - IJ_ULTIMATE=true
    - USE_PANTS_TO_COMPILE=false
    - USE_ISOLATED_STRATEGY=false
    - PANTS_SHA=91b8038 TEST_SET=integration # 0.0.44
    - PANTS_SHA=9459369 TEST_SET=integration # 0.0.43
    - PANTS_SHA=16c0c71 TEST_SET=integration # 0.0.42
    - PANTS_SHA=565a786 TEST_SET=integration # 0.0.41
    - PANTS_SHA=bde6007 TEST_SET=integration # 0.0.40
    - PANTS_SHA=bdc6820 TEST_SET=integration # 0.0.39
    - PANTS_SHA=047b149 TEST_SET=integration # 0.0.38
    - PANTS_SHA=2a0316a TEST_SET=integration # 0.0.37
    - PANTS_SHA=261bb71 TEST_SET=integration # 0.0.36
    - PANTS_SHA=69a9561 TEST_SET=integration # 0.0.35
    - PANTS_SHA=c2342bb TEST_SET=integration # 0.0.34

script:
  - ./scripts/run-tests-ci.sh
  - ./scripts/run-custom-integration.sh
      -r ./.cache/pants
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
